[project]
name = "fashion-brand-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flappy-bird-gymnasium>=0.4.0",
    "tensorflow>=2.18.0",
    "torch>=2.5.1",
]
